### ISSUE TITLE
Is this plugin deprecated?

### ISSUE THREAD

**Issue by tom-lord** [joker1007/vim-ruby-heredoc-syntax#1]
I encountered this syntax highlighting issue, googled the problem and tried using the plugin.

However, it did not work correctly - I was getting some weird `file not found` errors when using vim. Additionally, after updating my existing plugins, the original problem disappeared: There was an update to `vim-ruby` which fixed my issues: https://github.com/vim-ruby/vim-ruby/commit/a28f8df9f8444f82259fd331532c88524be8a61d

**Comment by naps62** [comment]
Same here. I'm having issues with Ruby 2.3's squiggly heredoc syntax. Was hoping this would solve it

**Comment by zerowidth** [comment]
I've got a fix for the squiggly heredoc in #3.

**Comment by joker1007** [comment]
Thanks a lot!!
I'm very sorry for no response.

**Comment by joker1007** [comment]
I merged #3.
